using AutoMapper;
using System.Collections.Generic;

namespace News0.Application.Mapping
{
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            CreateMap<Domain.Entities.PostTranslation, Domain.Dtos.PostDto>()
                .ForMember(dest => dest.Language, opt => opt.MapFrom(src => src.Language.Name));
            CreateMap<Domain.Dtos.PostDto, Domain.Entities.PostTranslation>()
                .ForMember(dest => dest.LanguageId, opt => opt.MapFrom(src => src.LanguageId))
                .ForMember(dest => dest.Language, opt => opt.Ignore());
            CreateMap<Domain.Dtos.PostDto, Domain.Entities.Post>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // Ignore mapping for Id as it will be generated by the database
                .ForMember(dest => dest.ImagePath, opt => opt.Ignore()) // Ignore mapping for ImagePath as it depends on the application logic
                .ForMember(dest => dest.CategoryId, opt => opt.MapFrom(src => src.CategoryId))
                .ForMember(dest => dest.Category, opt => opt.Ignore());

            CreateMap<Domain.Entities.Category, Domain.Dtos.CategoryDto>();
            CreateMap<Domain.Dtos.CategoryDto, Domain.Entities.Category>();

            CreateMap<Domain.Entities.Language, Domain.Dtos.LanguageDto>();
            CreateMap<Domain.Dtos.LanguageDto, Domain.Entities.Language>();
        }
    }
}
